name: Docker Build and Publish
on:
  push:
    branches: [main] # Trigger this workflow on pushes to the main branch
  pull_request:
    branches: [main] # Trigger this workflow on pull requests targeting the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Allows the workflow to push to Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-web-image:${{ github.sha }}
          latest: true # Also tag as latest on main branch pushes

      - name: Image details
        if: steps.docker_build_push.outputs.digest
        run: |
          echo "Digest: ${{ steps.docker_build_push.outputs.digest }}"
          echo "Tags: ${{ steps.docker_build_push.outputs.tags }}"
